// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taysvpmzhthqbnbnuidq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRheXN2cG16aHRocWJuYm51aWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NzA0NTEsImV4cCI6MjA4ODA0NjQ1MX0.4kq1ex-Aeq-Tiaa8iaAdFkMebg848_RbC6nKOfMsXg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});